services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./zesthub/db:/data/db
    environment: 
      POSTGRES_USER: zesthub
      POSTGRES_PASSWORD: B@loney1!
      POSTGRES_DB: zesthub

  client:
    container_name: zesthub
    build: juicymedia/zesthub
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DB_USERNAME: "zesthub"
      DB_PASSWORD: "B@loney1!"
      DB_HOST: "postgres"
      BASE_URL: "http://localhost:3000"