version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data    
    environment: 
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: portal

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    user: root
    expose:
      - 8025
    ports:
      - 8025:8025
      - 1025:1025
    healthcheck:
      test: echo | telnet 127.0.0.1 1025

volumes: 
  pgdata: